name: build-and-deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: |
          dotnet publish -c Release -o publish
          
      - name: Prepare site
        run: |
          mkdir site
          cp -r publish/wwwroot/* site/

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
